name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: sandaruwagachchi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push generated snake files
        uses: EndBug/add-and-commit@v9
        with:
          message: "update contribution graph"
          add: "dist/*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
